### ISSUE TITLE
Exception: Can not access invalid handle or view

### ISSUE THREAD

**Issue by yesint** [njohner/ost_pymodules#1]
I'm trying to compute the elastic properties of mixed lipid bilayer using the example provided. I've produced [aligned trajectory](https://drive.google.com/open?id=1ulgnyUIz--45e_5tJrEqgMPwwBS8L4Uy) with align_trajectory_AllAtom_Bilayer.py and modified lipid_elastic_properties_AllAtom.py like this:

```
from ost import *
import os,sys
import numpy as npy
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt
sys.path.append("/home/semen/install/ost_pymodules-master") #Set path to the python modules
import lipid_analysis,trajectory_utilities

indir="elastic/output"
outdir="elastic/prop"
pdbname="MySystem_aligned"
trajname="MySystem_aligned"
filename_basis='tilt&splay_'

lipid_names='YOPE DYPE DOPE DOPC POPE DYPC YOPC POPC'.split()
water_name='TIP3'

head_group_dict={'YOPE':'aname=P,N',
                 'DYPE':'aname=P,N',
                 'DOPE':'aname=P,N',
                 'DOPC':'aname=P,N',
                 'POPE':'aname=P,N',
                 'DYPC':'aname=P,N',
                 'YOPC':'aname=P,N',
                 'POPC':'aname=P,N'}
                                  
tail_dict={'YOPE':'aname=C314,C315,C316,C216,C217,C218',
           'DYPE':'aname=C314,C315,C316,C214,C215,C216',
           'DOPE':'aname=C316,C317,C318,C216,C217,C218',
           'DOPC':'aname=C316,C317,C318,C216,C217,C218',
           'POPE':'aname=C316,C317,C318,C216,C217,C218',
           'DYPC':'aname=C314,C315,C316,C214,C215,C216',
           'YOPC':'aname=C314,C315,C316,C216,C217,C218',
           'POPC':'aname=C316,C317,C318,C216,C217,C218'}

distance_sele_dict={'YOPE':'aname=C22,C21,C23,C31,C32,C33',
                    'DYPE':'aname=C22,C21,C23,C31,C32,C33',
                    'DOPE':'aname=C22,C21,C23,C31,C32,C33',
                    'DOPC':'aname=C22,C21,C23,C31,C32,C33',
                    'POPE':'aname=C22,C21,C23,C31,C32,C33',
                    'DYPC':'aname=C22,C21,C23,C31,C32,C33',
                    'YOPC':'aname=C22,C21,C23,C31,C32,C33',
                    'POPC':'aname=C22,C21,C23,C31,C32,C33'}

distance_cutoff=10.0 
angle_cutoff=0.175 
within_size_normals=10.0
density_cutoff=0.3
density_stride=1

to_analyze="cname=A and rname=YOPE,DYPE,DOPE,DOPC,POPE,DYPC,YOPC,POPC"
to_ignore="cname!=A and rname=YOPE,DYPE,DOPE,DOPC,POPE,DYPC,YOPC,POPC"

lipid_area=70.0

prot_sele=None
sele_dict={}

# The rest of example  script is not modified
```

I'm getting the following error:

```
$ python lipid_elastic_properties_AllAtom.py 
Generating the water and lipid densities and boundary surface
Calculating densities on 101 frames
Generating water density
Traceback (most recent call last):
  File "lipid_elastic_properties_AllAtom.py", line 135, in <module>
    outdir,density_cutoff,prot_sele,density_stride,tilt_bool_prop,splay_bool_prop,filename_basis,sele_dict)
  File "/home/semen/install/ost_pymodules-master/lipid_analysis.py", line 455, in AnalyzeLipidTiltAndSplay
    density_stride,within_size_normals,filename_basis)
  File "/home/semen/install/ost_pymodules-master/lipid_analysis.py", line 202, in GetBoundaryBetweenViews
    (water_filtered,lipid_filtered,boundary_filtered)=CalculateInterfaceFromTraj(t2,waters,lipids,False,None,None,10,density_cutoff,outdir,filename_basis)
  File "/home/semen/install/ost_pymodules-master/trajectory_utilities.py", line 454, in CalculateInterfaceFromTraj
    water_den=density_alg.CreateDensityMapFromTrajectory(t,waters,stride=stride)
  File "/home/semen/install/ost_pymodules-master/density_alg.py", line 105, in CreateDensityMapFromTrajectory
    sele_view=t.GetEntity().CreateFullView()
Exception: Can not access invalid handle or view
```

Could you please explain me what I'm doing wrong?

**Comment by njohner** [comment]
Hi,

Can you please send your whole input file? And if possible maybe a sample input, or at least your pdb?
Just the error message is not quite enough to be sure, but I’d say that one of your selections gave an empty view for some reason, so maybe run the script in interactive mode and check that your selections work properly.

I’m not working in academia anymore and I’m pretty busy right now, so it might take some time for me to get back to you.

Best,

Niklaus

--
4teamwork AG
Niklaus Johner
Software Developper
Dammweg 9
CH-3013 Bern
Tel +41 31 511 04 00
n.johner@4teamwork.ch <mailto:n.johner@4teamwork.ch>
www.4teamwork.ch <https://www.4teamwork.ch/>
Folgen Sie uns auf Twitter: @4teamwork <https://twitter.com/4teamwork>

**Comment by yesint** [comment]
Hi, Niklaus,
The link to trajectories is in the first post at top (link to google drive). Here is it again: https://drive.google.com/open?id=1ulgnyUIz--45e_5tJrEqgMPwwBS8L4Uy 
The script is attached.

[z.zip](https://github.com/njohner/ost_pymodules/files/1481964/z.zip)

**Comment by njohner** [comment]
Oh, I was reading your message in my mail box, where for some reason the google-drive links are not displayed... I'm taking a look at it now

**Comment by njohner** [comment]
The error comes from your selections, respectively from your pdb. Look at your pdb file and you'll see that you don't have any residue named with any of the lipid names you indicate, nor any TIP3 molecule. All your residue names are 3 letters long, so you probably put your structure through a software that cut the residue name to 3 (I think gromacs does that for example). So basically all your selections are empty. Also lipids like DOPC and DOPE are indistinguishable in your pdb.

**Comment by njohner** [comment]
Also your wrapping of the box doesn't seem right. Here a snapshot of the DOP lipids in the central unit cell (chain A). Some of your lipids are split. Make sure to keep your lipids whole before extending the unit cell.

![screen shot 2017-11-19 at 16 24 20](https://user-images.githubusercontent.com/7374243/32992035-0ce9e3f6-cd46-11e7-81dc-dec91039227a.png)

**Comment by yesint** [comment]
Thank you for quick responce! I see the problem. 
The treatment of periodicity in the code is actually very far from optimal, I must say. Making a system 8 times larger just because the backend library can't account for periodicity is, well, a kind of overkill.
After some time I've realized that it is much easier for me to implement your algorithm from scratch using our Pteros library (which has excellent support for periodicity and reads all file formats) than messing up with huge DCD trajectories and charmm-format PDBs, which we never use.
Of course we will cite your papers in proper way when it comes to publication.
Thank you very much again for quick reaction!

**Comment by njohner** [comment]
OpenStructure can handle periodic boundary conditions. There are several reasons why I handled the periodic boundary conditions the way I did in the lipid analysis code. First, once you align your trajectories, you can't store the periodic boundaries in the trajectory anymore (because the unit vectors are not pointing along xyz anymore, and trajectory file formats only support boundary conditions for which the first axis is along x). This is usually not a problem for planar bilayers, depending on how you align your trajectories. But I used the code for more complex lipidic systems, where periodic boundaries were not orthogonal. Moreover for these systems alignment was done using an optimisation on lipid and water densities, so there you combine non-orthogonal boundary conditions with none of the unit cell vectors along the x axis, and you have to calculate density maps for these, as well as be able to find nearest neighbours afterwards. As the alignment was what took most of the computational time anyway, and extending the system does mainly cost memory, this was an easy and safe way of treating the periodic boundary conditions.

Good luck and best!
